# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20170302_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='userProfile',
        ),
    ]
