# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20170304_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
